version: 2
references:
  default_container_config: &default_container_config
    docker:
      - image: node:lts

  attach_workspace: &attach_workspace
    attach_workspace:
      at: ~/project

  npm_cache_key: &npm_cache_key v1-dependency-npm-{{ checksum "package-lock.json" }}

  # ssh_cache_key: &ssh_cache_key vvc-rev{{ .Revision }}

  # restore_ssh: &restore_ssh
  #   restore_cache:
  #     keys:
  #       - *ssh_cache_key

  restore_node_modules: &restore_node_modules
    restore_cache:
      keys:
        - *npm_cache_key
        - v1-dependency-npm-

  cache_node_modules: &cache_node_modules
    save_cache:
      key: *npm_cache_key
      paths:
        - $HOME/.npm

jobs:
  install:
    <<: *default_container_config
    steps:
      - checkout
      # - save_cache:
      #     key: *ssh_cache_key
      #     paths:
      #       - ~/.ssh
      - *restore_node_modules
      - run:
          name: Install dependencies
          command: npm ci
      - *cache_node_modules
      - persist_to_workspace:
          root: .
          paths:
            - .

  test:
    <<: *default_container_config
    steps:
      - *attach_workspace
      - run:
          name: Run tests
          command: npm test

  release_npm:
    <<: *default_container_config
    steps:
      - *attach_workspace
      # - *restore_ssh
      # - run:
      #     name: Remove read key
      #     command: ssh-add -D
      # - add_ssh_keys:
      #     fingerprints:
      #       - "55:3a:fa:df:9d:17:8a:88:be:96:da:e1:1b:78:12:7a"
      # - run:
      #     name: Set Git config
      #     command: git config --global user.email "data.journalism.development+ci@ft.com" && git config --global user.name FT-DJD
      - run:
          name: Build
          command: npm run build
      - run:
          name: Publish npm package
          command: npx semantic-release

  release_ghpr:
    <<: *default_container_config
    steps:
      - *attach_workspace
      - run:
          name: Build
          command: npm run build
      - run:
          name: Set env vars
          command: export NPM_CONFIG_REGISTRY="https://npm.pkg.github.com/" && export NPM_TOKEN="${GHPR_TOKEN}"

      - run:
          name: Publish npm package
          command: npx semantic-release

workflows:
  version: 2
  build-and-release:
    jobs:
      - install
      # - test:
      #     requires:
      #       - install
      - release_npm:
          filters:
            branches:
              only: master
          requires:
            - install
            # - test
      - release_ghpr:
          filters:
            branches:
              only: master
          requires:
            - install
            # - test
